## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search\\WeatherPy_vacation.csv")
vacation_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,2,Kavieng,PG,81.46,moderate rain,-2.5744,150.7967,Nusa Island Retreat
1,15,Vaini,TO,82.56,few clouds,-21.2000,-175.2000,Keleti Beach Resort
2,23,Biak,ID,83.48,overcast clouds,-0.9131,122.8766,Penginapan Kim
3,26,Touros,BR,77.90,scattered clouds,-5.1989,-35.4608,INN NEW HORIZON
4,27,Hilo,US,76.73,moderate rain,19.7297,-155.0900,Hilo Hawaiian Hotel
...,...,...,...,...,...,...,...,...
170,694,Kendari,ID,86.76,overcast clouds,-3.9450,122.4989,Hotel Wixel
171,697,Dingle,PH,81.41,overcast clouds,10.9995,122.6711,SEGAYA PROPERTY
172,698,Gold Coast,AU,86.16,overcast clouds,-28.0000,153.4333,Mantra Towers of Chevron Surfers Paradise
173,700,Okitipupa,NG,76.03,overcast clouds,6.5047,4.7839,Coastal Hotel & Suites
174,701,Aden,YE,78.35,few clouds,12.7794,45.0367,Sama Emirate Hotel

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# choose four cities close together and in the same country.
vacation_df.loc[vacation_df.Country == 'BR']

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,26,Touros,BR,77.90,scattered clouds,-5.1989,-35.4608,INN NEW HORIZON
7,49,Cabedelo,BR,77.67,clear sky,-6.9811,-34.8339,Hotel Pigalle
34,155,Maceio,BR,76.44,broken clouds,-9.6658,-35.7353,Poutur Pousada
57,263,Camocim,BR,80.78,few clouds,-2.9022,-40.8411,Ilha Praia Hotel
62,286,Manaus,BR,77.50,broken clouds,-3.1019,-60.0250,Manaus Hotéis Millennium
63,293,Belmonte,BR,75.70,moderate rain,-15.8631,-38.8828,Pousada Monte Carmelo O Pão
119,517,Coxim,BR,79.65,scattered clouds,-18.5067,-54.7600,Hotel Avenida
122,522,Gilbues,BR,77.20,overcast clouds,-9.8317,-45.3439,Hotel Camapuã
129,536,Soure,BR,78.93,overcast clouds,-0.7167,-48.5233,Casarão da Amazônia
130,545,Ipixuna,BR,76.95,moderate rain,-1.7625,-48.8043,Casa da Oscarina
142,607,Jardim,BR,77.04,overcast clouds,-21.4803,-56.1381,Estancia Hotel - Jardim MS
145,613,Oriximina,BR,75.61,overcast clouds,-1.7656,-55.8661,Pousada Tia Amélia
147,628,Acarau,BR,80.76,broken clouds,-2.8856,-40.1200,castelo pizzaria
167,691,Natal,BR,79.02,few clouds,-5.7950,-35.2094,Villa Park Hotel | Natal

In [46]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df.City =='Touros']
vacation_end = vacation_df.loc[vacation_df.City =='Touros']
vacation_stop1 = vacation_df.loc[vacation_df.City =='Cabedelo']
vacation_stop2 = vacation_df.loc[vacation_df.City =='Maceio'] 
vacation_stop3 = vacation_df.loc[vacation_df.City =='Camocim'] 
vacation_stop1

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
7,49,Cabedelo,BR,77.67,clear sky,-6.9811,-34.8339,Hotel Pigalle

In [47]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start['Lat'].to_numpy()[0], vacation_start['Lng'].to_numpy()[0]
end = vacation_end['Lat'].to_numpy()[0], vacation_end['Lng'].to_numpy()[0]
stop1 = vacation_stop1['Lat'].to_numpy()[0], vacation_stop1['Lng'].to_numpy()[0]
stop2 = vacation_stop2['Lat'].to_numpy()[0], vacation_stop2['Lng'].to_numpy()[0]
stop3 = vacation_stop3['Lat'].to_numpy()[0], vacation_stop3['Lng'].to_numpy()[0]

print(stop1)
print(type(stop1))

(-6.9811, -34.8339)
<class 'tuple'>

In [48]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
Brazil_vacation_roadtrip = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')
fig.add_layer(Brazil_vacation_roadtrip)
fig

Figure(layout=FigureLayout(height='420px'))

In [49]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,26,Touros,BR,77.90,scattered clouds,-5.1989,-35.4608,INN NEW HORIZON
1,49,Cabedelo,BR,77.67,clear sky,-6.9811,-34.8339,Hotel Pigalle
2,155,Maceio,BR,76.44,broken clouds,-9.6658,-35.7353,Poutur Pousada
3,263,Camocim,BR,80.78,few clouds,-2.9022,-40.8411,Ilha Praia Hotel

In [56]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description, <dt>Max Temp</dt> </dt><dd>{Current Description} & {Max Temp} °F</dd>

</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [58]:
# 11a. Add a marker layer for each city to the map.

max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=2)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)


# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))